# Generated by Django 4.2.4 on 2023-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=300)),
                ('image', models.ImageField(max_length=900, upload_to='')),
            ],
        ),
    ]
